- hosts: all
  become: true
  roles:
    - role: geerlingguy.nfs
      nfs_exports:
        - "/var/opt/gitlab/git-data {{ cidr }}(rw,sync,no_root_squash)"
        - "/var/opt/gitlab/.ssh {{ cidr }})rw,sync,no_root_squash)"
        - "/var/opt/gitlab/gitlab-rails/uploads {{ cidr}}(rw,sync,no_root_squash)"
        - "/var/opt/gitlab/gitlab-rails/shared {{ cidr }}((rw,sync,no_root_squash)"
        - "/var/opt/gitlab/gitlab-ci/builds {{ cidr }}(rw,sync,no_root_squash)"