- hosts: all
  become: true
  tasks:
    - name: Add cassandra repo
      yum_repository:
        name: cassandra
        description: Apache Cassandra
        baseurl: https://www.apache.org/dist/cassandra/redhat/311x/
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://www.apache.org/dist/cassandra/KEYS
    - name: yum update
      yum:
        name: '*'
        state: latest
    - name: install packages
      yum:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - java-1.8.0-openjdk
        - cassandra
    - name: Delete files. See here - https://www.digitalocean.com/community/tutorials/how-to-run-a-multi-node-cluster-database-with-cassandra-on-ubuntu-14-04
      shell: rm -rf /var/lib/cassandra/data/system/*
      args:
        warn: no